### ISSUE TITLE
Can't start up ，启动不了 能帮助支持一下吗

### ISSUE THREAD

**Issue by raynent** [ChainUp-Custody/mpc-co-signer#1]
`./startup.sh
Please enter your password:
Startup Program...

[root@ip co-signer]# ls
conf  co-signer  install.sh  nohup.out  startup.sh
[root@ip-192-168-70-62 co-signer]# tail -f nohup.out
chainup.com/mpc-co-signer/startup/nodes.LoadNodes()
        /data/jenkins_data/workspace/Pipeline-mpc-co-signer（ego build）/startup/nodes/nodes.go:33 +0x3cd
chainup.com/mpc-co-signer/startup.loadConfig()
        /data/jenkins_data/workspace/Pipeline-mpc-co-signer（ego build）/startup/server.go:49 +0xbe
chainup.com/mpc-co-signer/startup.startServer()
        /data/jenkins_data/workspace/Pipeline-mpc-co-signer（ego build）/startup/server.go:20 +0x2d
chainup.com/mpc-co-signer/startup.Init()
        /data/jenkins_data/workspace/Pipeline-mpc-co-signer（ego build）/startup/startup.go:55 +0x19
main.main()
        /data/jenkins_data/workspace/Pipeline-mpc-co-signer（ego build）/main.go:17 +0xce
`

**Comment by raynent** [comment]
config file
## Main Configuration Information
main:
    ## [Required] Co-signer service IP address
    tcp: "0.0.0.0:28888"
    ## [Required] Encrypted storage file used by v1.1.x version
    keystore_file: "conf/keystore.json"

## Custody System
custody_service:
    ## [Required] app_id, obtained after creating a merchant
    app_id: "111931"
    ## [Required] api domain address, see interface documentation
    domain: "https://openapi.chainup.com/"
    ## [Optional] Request and response language, supporting zh_CN and en_US
    language: "en_US"

## Client System
custom_service:
    ## [Optional] Withdrawal callback client system address for signature confirmation before signing, details see: https://custodydocs-zh.chainup.com/api-references/mpc-apis/co-signer/callback/withdraw, mandatory sign verification when not configured
    withdraw_callback_url: ""
    ## [Optional] Web3 transaction callback client system address for signature confirmation before signing, details see: https://custodydocs-zh.chainup.com/api-references/mpc-apis/co-signer/callback/web3, mandatory sign verification when not configured
    web3_callback_url: ""

**Comment by bevinhex** [comment]
in my case, when keys aren't set correctly cosigner will crash as well, make sure those private/public keys are set correctly and see if it is the case for you
also if the machine does not support sgx and you are trying to use ego signed sgx version, it will crash too
